export type Locale = 'en' | 'de';

const en = {
  brand: 'VisCon',
  tagline: 'Sign in with your ETH student account to study with the lectures.',
  login: 'Log in', register: 'Create account',
  identifier: 'ETH username or email', identifierHint: 'riordache, riordache@ethz.ch or riordache@student.ethz.ch',
  password: 'Password', newPassword: 'New password', passwordHint: 'At least 10 characters.', showPassword: 'Show password', hidePassword: 'Hide password',
  code: 'Verification code', codeHint: 'The 6-digit code from the email.',
  forgot: 'Forgot password?', back: 'Back',
  submitLogin: 'Log in', submitRegister: 'Send verification code', submitConfirm: 'Verify and continue',
  submitForgot: 'Send reset code', submitReset: 'Set new password',
  confirmTitle: 'Check your ETH inbox', confirmBody: (to: string) => `We sent a 6-digit code to ${to}. It expires in 10 minutes.`,
  confirmPending: 'We need to confirm this ETH mailbox before you can continue.',
  resend: 'Send a new code', resendIn: (s: number) => `New code in ${s}s`, resent: 'If a registration is waiting, a new code is on its way.',
  forgotTitle: 'Reset your password', forgotBody: 'Enter your ETH username or email. If an account exists, we send a code to its student mailbox.',
  resetTitle: 'Choose a new password', resetBody: 'Enter the code from the email and your new password. You will be signed out on all devices.',
  resetDone: 'Password updated. Log in with your new password.',
  studentNote: 'Codes go to your @student.ethz.ch mailbox.',
  logout: 'Log out', loggedInAs: 'Signed in as',
  checking: 'Checking your account…', retry: 'Try again',
  unreachable: 'The server cannot be reached right now.',
  sessionEnded: 'Your session ended. Log in again to continue.',
  errors: {
    invalid_identifier: 'Enter your ETH username or your @ethz.ch / @student.ethz.ch address.',
    weak_password: 'Choose a password with at least 10 characters that does not contain your username.',
    account_exists: 'An account for this ETH username already exists. Log in, or reset your password.',
    already_linked: 'This profile already belongs to another account. Log out first.',
    invalid_credentials: 'Wrong username or password.',
    not_verified: 'Confirm your ETH email first. We sent you a code.',
    rate_limited: 'Too many attempts. Please wait a moment and try again.',
    too_many_attempts: 'Too many wrong codes. Request a new one.',
    invalid_or_expired: 'That code is wrong or has expired. Request a new one.',
    mail_unavailable: 'The email could not be sent right now. Try again later.',
    network: 'The server cannot be reached right now.',
    server: 'Something went wrong. Try again.',
  } as Record<string, string>,
};

const de: typeof en = {
  brand: 'VisCon',
  tagline: 'Melde dich mit deinem ETH-Studierendenkonto an, um mit den Vorlesungen zu lernen.',
  login: 'Anmelden', register: 'Konto erstellen',
  identifier: 'ETH-Benutzername oder E-Mail', identifierHint: 'riordache, riordache@ethz.ch oder riordache@student.ethz.ch',
  password: 'Passwort', newPassword: 'Neues Passwort', passwordHint: 'Mindestens 10 Zeichen.', showPassword: 'Passwort anzeigen', hidePassword: 'Passwort verbergen',
  code: 'Bestätigungscode', codeHint: 'Der 6-stellige Code aus der E-Mail.',
  forgot: 'Passwort vergessen?', back: 'Zurück',
  submitLogin: 'Anmelden', submitRegister: 'Bestätigungscode senden', submitConfirm: 'Bestätigen und weiter',
  submitForgot: 'Code zum Zurücksetzen senden', submitReset: 'Neues Passwort speichern',
  confirmTitle: 'Prüfe dein ETH-Postfach', confirmBody: (to: string) => `Wir haben einen 6-stelligen Code an ${to} gesendet. Er ist 10 Minuten gültig.`,
  confirmPending: 'Wir müssen dieses ETH-Postfach bestätigen, bevor du fortfahren kannst.',
  resend: 'Neuen Code senden', resendIn: (s: number) => `Neuer Code in ${s} s`, resent: 'Falls eine Registrierung wartet, ist ein neuer Code unterwegs.',
  forgotTitle: 'Passwort zurücksetzen', forgotBody: 'Gib deinen ETH-Benutzernamen oder deine E-Mail ein. Falls ein Konto existiert, senden wir einen Code an das Studierendenpostfach.',
  resetTitle: 'Neues Passwort wählen', resetBody: 'Gib den Code aus der E-Mail und dein neues Passwort ein. Du wirst auf allen Geräten abgemeldet.',
  resetDone: 'Passwort aktualisiert. Melde dich mit dem neuen Passwort an.',
  studentNote: 'Codes gehen an dein @student.ethz.ch-Postfach.',
  logout: 'Abmelden', loggedInAs: 'Angemeldet als',
  checking: 'Konto wird geprüft…', retry: 'Erneut versuchen',
  unreachable: 'Der Server ist gerade nicht erreichbar.',
  sessionEnded: 'Deine Sitzung ist abgelaufen. Melde dich erneut an.',
  errors: {
    invalid_identifier: 'Gib deinen ETH-Benutzernamen oder deine @ethz.ch- bzw. @student.ethz.ch-Adresse ein.',
    weak_password: 'Wähle ein Passwort mit mindestens 10 Zeichen, das deinen Benutzernamen nicht enthält.',
    account_exists: 'Für diesen ETH-Benutzernamen gibt es schon ein Konto. Melde dich an oder setze dein Passwort zurück.',
    already_linked: 'Dieses Profil gehört schon zu einem anderen Konto. Melde dich zuerst ab.',
    invalid_credentials: 'Benutzername oder Passwort ist falsch.',
    not_verified: 'Bestätige zuerst deine ETH-E-Mail. Wir haben dir einen Code gesendet.',
    rate_limited: 'Zu viele Versuche. Warte einen Moment und versuche es erneut.',
    too_many_attempts: 'Zu viele falsche Codes. Fordere einen neuen an.',
    invalid_or_expired: 'Der Code ist falsch oder abgelaufen. Fordere einen neuen an.',
    mail_unavailable: 'Die E-Mail konnte gerade nicht gesendet werden. Versuche es später erneut.',
    network: 'Der Server ist gerade nicht erreichbar.',
    server: 'Etwas ist schiefgelaufen. Versuche es erneut.',
  },
};

export const strings: Record<Locale, typeof en> = { en, de };
